# Generated by Django 6.0.1 on 2026-01-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
    ]
